k3d-io/k3d

main.go
Besides creating a helper method to run exec this also pipe stdout/err from
each call to the screen so that the user gets better feedback on what is
happening and why it might have failed.
After cluster create just print a simple command line to the screen to help
the user along.
Cluster create output now looks like
```
$ ./k3d-go c
2019/04/03 10:42:44 Creating cluster [k3s_default]
2019/04/03 10:42:44 Running command: [docker run --name k3s_default -e K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml --publish 6443:6443 --privileged -d rancher/k3s:v0.3.0 server --https-listen-port 6443]
0cead32193f1d3abc9219e85008a9230bc551921ba9c41a997a3bb542e3f8f0d
2019/04/03 10:42:44 SUCCESS: created cluster [k3s_default]
2019/04/03 10:42:44 You can now use the cluster with:
export KUBECONFIG="$(./k3d-go …
```
=> Improve logging of command and add help text for users

README.md, cli/commands.go, main.go
**What changed?**
* Re-ordered the arguments for the docker command in `CreateCluster` function
* New Flags for `create` command:
- `--env`, `-e` for passing additional environment variables to docker
- `--server-arg`, `-x` for passing additional  arguments to the k3s server command
* Shorthand notation for `delete` command: `-del`
Let me know, what you think @zeerorg and @ibuildthecloud
=> add server-arg and env flags

Makefile, README.md
This patch set should improve the user experience of first time building.  When running "make build" from a freshly cloned repo, I got the following error:
Makefile:71: *** recipe commences before first target.  Stop. 
The patch set improve the makefile by introduce the install-tools target.
=> Makefile cleanup

cli/commands.go
Before this change, command:
$ k3d create -name test
$ k3d get-kubeconfig
Produces the following error message:
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/rancher/k3d/cli.GetKubeConfig(0xc00031a160, 0x0, 0x0)
/Users/azhou/projs/k3d/cli/commands.go:335 +0x105d
github.com/urfave/cli.HandleAction(0x13e7ca0, 0x148f0b0, 0xc00031a160, 0xc000304000, 0x0)
/Users/azhou/projs/rcloud/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x1477cb5, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1480cd8, 0x23, 0x0, ...)
/Users/azhou/projs/rcloud/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x996
github.com/urfave/cli.(*App).Run(0xc0000bc1a0, 0xc00000e060, 0x2, 0x2, 0x0, 0x0)
/Users/azhou/projs/rcloud/pkg/mod/github.com/urfave/cli@v1.20.0/app. …
=> [BUGFIX] cli: Improve error message for 'k3d get-kubeconfig'

version/version.go
Added a small fix to add the default version for k3s docker image, `v0.4.0` as per my issue #23
=> [BUGFIX] add default k3s version (honored by go install)

cli/commands.go, main.go
Attempt to properly fix the bug mentioned in #34
=> Clustername

cli/commands.go, cli/container.go, main.go
Add support for --publish option (--add-port is an alias to this option).
With those patches, we can create a cluster with the following command line:
$) bin/k3d create -n test --publish 8080:8080 --publish 9090:30090/udp --workers 1
$) docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                                                     NAMES
8e8fd4582cfa        rancher/k3s:v0.5.0   "/bin/k3s agent"         6 seconds ago       Up 5 seconds        0.0.0.0:8081->8080/tcp, 0.0.0.0:9091->30090/udp                           k3d-test-worker-0
c08480a9efef        rancher/k3s:v0.5.0   "/bin/k3s server --h…"   7 seconds ago       Up 6 seconds        0.0.0.0:6443->6443/tcp, 0.0.0.0:8080->8080/tcp, …
=> [Feature] Add --publish/--add-port flag for port mappings

cli/commands.go
Delete a cluster if it is not started due to port conflicts or any other unforseen error
Signed-off-by: Rishabh Gupta <r.g.gupta@outlook.com>
=> Delete a cluster if it encounters error when starting

cli/config.go
Make list output center aligne. It is slightly eaier to read.
Before the commit:
$ bin/k3d list --all
+-------------+------------------------------+---------+---------+
|    NAME     |            IMAGE             | STATUS  | WORKERS |
+-------------+------------------------------+---------+---------+
| k3s-default | docker.io/rancher/k3s:v0.5.0 | running | 2/2     |
+-------------+------------------------------+---------+---------+
After this commit:
$ bin/k3d list --all
+-------------+------------------------------+---------+---------+
|    NAME     |            IMAGE             | STATUS  | WORKERS |
+-------------+------------------------------+---------+---------+
| k3s-default | docker.io/rancher/k3s:v0.5.0 | running |   2/2   | …
=> [Enhancement] Center align list output

cli/commands.go, cli/config.go, cli/container.go, cli/port.go, cli/util.go, main.go
This PR changes quite a lot of things and builds on top of PR #32 .
It's another attempt to improve the situation regarding issue #11.
**Changes:**
* `--publish`/`--add-port` syntax is now `[ip:][host-port:]container-port[/protocol]@node-specifier`, where container-port and node-specifier are mandatory and node-specifier can be one or multiple
- node-specifier can be either one of `all`, `server`, `worker` or the name of a node that will be created (easier naming will follow, since e.g. `k3d-some-test-name-worker-0` is not convenient to use)
- since the node-specifier is mandatory, we won't automatically map ports to multiple nodes
* `--api-port`/`-a` is now the default to set the K8s ApiPort mapping, since we want to re-use `--port`/`-p` for the functionality of `--publish`/`--add-port` …
=> [Feature] Enhanced port mapping (node-specifiers, optional offset, ...)

cli/commands.go, main.go
Most k3d arguments are using in "stringSlice" style, allowing the
argument to supplied multiple times. Currently "volume" is an exception
to this style, require multiple arguments to be supplied in a single
argument, separated by comma.
This commit improve the k3d usability by improve the consistency of its
argument style.
=> [Enhancement] Allow the volume argument to be specified multiple times

cli/container.go
Thanks @zeerorg for the suggestion on possible container volume leak.
With out this fix the k3s container volumes are left in the reclaimable
state. This experiment confirms it:
$ docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              14                  0                   2.131GB             2.131GB (100%)
Containers          0                   0                   0B                  0B
Local Volumes       0                   0                   0B                  0B
Build Cache         0                   0                   0B                  0B
$ bin/k3d create; sleep 5; bin/k3d delete
$ docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images …
=> [Enhancement] Automatically reclaim k3s container volumes after a cluster is deleted

cli/cluster.go, cli/commands.go
It feels more natural to have the list command show all clusters by
default.
@zeerorg asked a question in the same area in #33.  I agree with his question as well. 
I often forgot to add --all flag and find myself wondering what happened to the stopped clusters.
=> [Enhancement] Make list command always show all clusters. Remove --all option

cli/commands.go, main.go
Use --wait <timeout> instead.
This simplify the command line, and allow us to recycle the '-t' option for other use down the road.
=> [Enhancement] Deprecate the --timeout option

cli/commands.go
Before this commit, when creating a cluster was not successful, some
resource may be lingering behind. This commit fixes those cases.
Now the cluster creation model is easier to understand. Either a cluster
is successfully created, or all resources created will be cleaned up.
The intention is to keep the "atomic create" model going forward for
k3d.
=> [Enhancement] Atomic create

cli/commands.go, cli/container.go, main.go
As mentioned in #15. 
When creating clusters with the --always-on flag, the cluster can
remain in the "running" state across the docker daemon restart.
Without this flag, a "running" cluster becomes "stopped" after docker
daemon restart.
Clusters stopped with 'k3d stop' command will remain stopped after
docker daemon restart.
=> [Feature] Implement --always-on flag for the create command

cli/commands.go
Co-authored-by: Thorsten Klein <iwilltry42@gmail.com>
@iwilltry42 pointed out that currnet error path calls os.Exit(1), which
does follow the normal CLI framework. This patch implements this
suggestion.
Add a closure fucntion deleteCluster() to reduce code duplication.
=> [Enhancement] Improve error handling for CreateCluster()

cli/commands.go
Now passes environment variables (like `HTTPS_PROXY`) to the workers.
=> Now passes the environment variables to the workers.

cli/cluster.go, cli/commands.go, cli/shell.go, main.go
After creating a cluster, k3d will display a hint on how to set the KUBECONFIG. Often the message scrolled away, and one has to either remember the syntax or hunt for the message. 
This PR implemented the 'bash' subcommand to make switch between cluster context easier.
To start a new shell with a cluster context do:
$ k3d bash -n <cluster-name> 
This will gave a new shell with KUBECONFIG set for the cluster. kubectl will just work with the intended cluster.  Use  'exit' to leave the shell
Also support a one liner use cases:
$ k3d bash -n <cluster-name> -e 'kubectl cluster-info' 
This is useful to quick issue commands against multiple clusters.
Limitations: 
* The PR only support bash,  If it is useful, I hope others will contribute support for more shells.
=> [Feature] Add Bash shell support

cli/commands.go, cli/shell.go, main.go
By default, the `shell` command now uses `auto`-mode, where it selects the shell based on the `$SHELL` environment variable. It then checks if that shell is supported and selects the required options from a map.
I also added support (options) for `zsh`.
=> [Feature] auto mode and zsh support for shell command

cli/container.go, cli/network.go
Should make sense since all container names are with the same prefix.
=> [Enhancement] Add k3d- prefix to docker network name

cli/cluster.go, cli/commands.go, cli/docker-machine.go
Also should fix #68.
Docker Toolbox uses a docker-machine to run docker containers.  This bug exposes the fact k3d does not recognize docker machine in general.  This PR adds support for docker machine, thus should also fix #68.
I don't usually use Docker Toolbox, or other docker machine set up. This PR could benefit from more testing from those who do use them.
=> [Feature] Docker machine

cli/cluster.go, cli/commands.go, cli/container.go, cli/util.go, main.go
Add support for --api-port to take [host]:port as argument.
=> [Enhancement] Api port

cli/commands.go, main.go
We have been giving user warnings about --timeout going away for a
while. Now fully deprecate it.
Use -t for --wait option
Move -w from --wait to --workers. Many users of K3d generate multi-node
clusters, -w will make their life easier.
=> [Enhancement] Deprecate --timeout, shift short hand options around

cli/docker-machine.go
Triggered by bug report #78.
Currently, when the 'docker-machine' command fails, we only logs
"exit status 1'
Which is not very helpful in root cause analysis.
With this patch, the 'docker-machine' command's stderr output is also
logged.
$ export DOCKER_MACHINE_NAME=xx
$ k3d create
2019/06/13 16:45:31 Created cluster network with ID 6fc91e0e5e912443e6b847f113a6a0bb85ccd610e5232592296d4b199f0347cf
2019/06/13 16:45:31 Error executing 'docker-machine ip'
2019/06/13 16:45:31 Docker machine "xx" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
exit status 1
=> [Enhancement] Log more information when the docker-machine command fails

cli/commands.go
It turns out that docker client only pays attention to the following
environment variables:
DOCKER_HOST to set the url to the docker server.
DOCKER_API_VERSION to set the version of the API to reach, leave empty for latest.
DOCKER_CERT_PATH to load the TLS certificates from.
DOCKER_TLS_VERIFY to enable or disable TLS verification, off by default.
A miss configured DOCKER_MACHINE_NAME won't affect docker client, so k3d
should just ignore the error.
=> [Enhancement] Ignore docker-machine command line error

cli/commands.go
Fix for #87 - error should occur when current time is after start+timeout
=> Fix inverted timeout logic on create.

cli/cluster.go, cli/commands.go, cli/container.go, cli/image.go, cli/util.go, cli/volume.go, main.go, vendor/modules.txt
`k3d import-images` to import docker images from the used docker daemon into containerd inside the k3d nodes.
This is a new version of PR #83 which makes use of a named volume and an additional `k3d-tools` container.
1. upon k3d create, a named volume for storing images will be created and mounted on /images in all nodes (**NOTE**: this requires at least `--image rancher/k3s:v0.7.0-rc2` because of `ctr`)
2. user has nginx:local and redis:v2 cached locally after issuing docker build and wants to have them available to the k3d nodes (without having to push to a registry)
3. user issues `$ k3d import-images --cluster test-cluster nginx:local redis:v2` 
4. a helper container (currently iwilltry42/k3d-tools:v0.0.1) will be spawned, mounting the same volume as the nodes and …
=> [Feature] import images from docker daemon into k3d

docs/examples.md
This is a summary for the slack conversation around creating a local unsecure registry that can be used from both the host and a cluster managed by k3d
=> [Doc] Added doc for running a local unsecure registry

cli/commands.go, cli/container.go, main.go
Expose `--agent-arg` flag and forward those to k3s like we do for `--server-arg`.
There is an agent arg in the cluster spec, but it is not forwarded to the container config when starting the container. This change exposes the agent arg so that options passed to kubernetes components in the master container can also be passed to workers.
Fixes #86
=> Expose `--agent-arg` like `--server-arg`

README.md, install.sh
Hey :wave:,
this PR enables the install script to grab a specific release rather than "the latest".
Use case: Predictable feature set by relying on a specific version. 
Feedback is much appreciated :purple_heart:  
Kind regards,
Peter
=> Allow passing `TAG` to install a specific release

cli/cluster.go, cli/commands.go, cli/container.go, cli/docker-machine.go, cli/image.go, cli/network.go, cli/port.go, main.go
=> [WIP] Replace log with logrus

Makefile
Small Makefile enhancement to make sure we use `$(GO)` everywhere.
=> makefile: consistent use of go option

docs/examples.md
Since #116 was merged, users whose Docker's `data-root` is on a filesystem k3s doesn't "appreciate" working with can work around this limitation by slipping a volume with a supported filesystem (like ext4, for example) under each node's `/var/lib/rancher/k3s`. This pull request provides an example of doing so using a loopback volume driver.
=> Provide an example that allows running k3d on filesystems k3s doesn't like.

cli/commands.go
If you are writing a script to launch k3s clusters checking the exit
code of `get-kubeconfig` is an easy way to tell if the kubeconfig is
available for use.
=> Only ignore get-kubeconfig error when !all

cli/container.go
k3s is not a child subreaper so running k3s as PID 1 will result
in zombie processes.  Using `docker run --init` works around this
issue.
=> Launch containers with init

cli/cluster.go
The kubeconfig generated by `docker.io/rancher/k3s:v0.10.2` or earlier sets the `cluster.server` address to `127.0.0.1`. Previously this seems to have been `localhost`. And we only replace `localhost` with the correct address for our local kubeconfig.
The error I encountered:
```
$ k3d --version
k3d version v1.3.4
$ docker-machine --version
docker-machine version 0.16.1, build cce350d7
$ docker --version
Docker version 19.03.1, build 74b1e89
$ k3d create
INFO[0000] Created cluster network with ID 649d6f34b84a4df16d2524f0ea0ce69cd4f964a79ae56e2a07bb1ee11d1fce50
INFO[0001] Add TLS SAN for 192.168.99.100
INFO[0001] Created docker volume  k3d-k3s-default-images
INFO[0001] Creating cluster [k3s-default]
INFO[0001] Creating server using docker.io/rancher/k3s:v0.10.2...
INFO[0001] Pulling image …
```
=> Fix kubeconfig not pointing to correct host when using docker-machine

cli/commands.go, cli/container.go, cli/label.go, cli/port.go, cli/types.go, main.go
Some service discovery systems are using docker labels to configure DNS, load-balancing, monitoring, metering ... (ie. [dalidock](https://github.com/lionelnicolas/dalidock) , [traefik](https://docs.traefik.io/providers/docker/#routing-configuration) ...).
This PR introduce ability to set arbitrary docker labels for worker nodes using a new `--label` argument to `k3s create` and `k3d add-node`.
=> [Feature] add ability to set docker labels on worker nodes

cli/commands.go, cli/container.go, cli/registry.go, cli/types.go, cli/util.go, main.go, tests/01-basic.sh, tests/02-registry.sh, tests/common.sh
We are currently assuming the `registries.yaml` is located at `~/.k3d/registries.yaml`. This option gives the possibility of customizing this file. It also allows users to customize private registries per cluster.
=> [Feature] Add flag for customizing the global registries file

cli/commands.go, cli/network.go, main.go, tests/01-basic.sh
New option, `--prune`, for `delete`. When forcing a delete, all the containers connected to the k3d network will be disconnected before removing the network.
=> [Feature] New --prune option for delete

cli/commands.go, cli/registry.go, cli/types.go, cli/volume.go, main.go, tests/02-registry.sh, tests/common.sh
* New `--registry-volume` option (for `create`) for using an specific volume in the registry. It can be used for specifying a user-provided volume, but the volume will be created if it does not exist.
* New `--keep-registry-volume` (for `delete`) for preventing the registry volume from being deleted. Users can create new clusters that use that volume by using the `--registry-volume` argument.
=> [Feature] Options for keeping/re-using a specific volume for the registry

cli/commands.go
Little fix :
According to this https://github.com/rancher/k3s/blob/master/README.md#L55
I think K3S cluster secret variable is K3S_CLUSTER_SECRET.
=> [Fix] K3S_SECRET env variable to K3S_CLUSTER_SECRET

cmd/create/createCluster.go, cmd/create/createNode.go, pkg/cluster/cluster.go, pkg/cluster/kubeconfig.go, pkg/cluster/node.go, pkg/types/types.go, proxy/Dockerfile, proxy/conf.d/nginx.toml, proxy/nginx-proxy, proxy/templates/nginx.tmpl, tests/test_multi_master.sh
We're now creating a nginx proxy container in front of every cluster which proxies requests to the master nodes of that cluster. That way, we only need to expose a single port for multiple master nodes.
Discussed with @galal-hussein, based on PR #214, thanks!
=> [v3/Feature] Add cluster-loadbalancer

Makefile
- up to now, there's no `latest` tag for k3s docker images
- the latest tag on GitHub (which has been used so far) may be an old k8s version (e.g. right now, it's 1.16.x instead of 1.18.x)
Use the stable channel of the channel server and parse the tag from the returned URL (href).
Bonus: no more GitHub API calls that may fail :+1: 
Thanks @davidnuzik for telling me about the channel server :)
=> [Enhancement] installScript: use channel server to fetch latest stable k3s version

cmd/start/startCluster.go, docs/usage/commands.md, pkg/cluster/cluster.go, pkg/cluster/node.go, pkg/runtimes/containerd/node.go, pkg/runtimes/docker/node.go, pkg/runtimes/runtime.go, pkg/types/types.go, tests/test_full_lifecycle.sh
- functionality mostly copy-pasted from createCluster
Fixes #222
=> [Feature] v3/startCluster: add --wait and --timeout

cmd/create/createCluster.go, cmd/create/createNode.go, cmd/delete/deleteCluster.go, cmd/delete/deleteNode.go, cmd/get/getCluster.go, cmd/get/getKubeconfig.go, cmd/get/getNode.go, cmd/load/loadImage.go, cmd/start/startCluster.go, cmd/start/startNode.go, cmd/stop/stopCluster.go, cmd/stop/stopNode.go, pkg/cluster/cluster.go, pkg/cluster/kubeconfig.go, pkg/cluster/loadbalancer.go, pkg/cluster/node.go, pkg/runtimes/containerd/kubeconfig.go, pkg/runtimes/containerd/network.go, pkg/runtimes/containerd/node.go, pkg/runtimes/containerd/volume.go, pkg/runtimes/docker/container.go, pkg/runtimes/docker/kubeconfig.go, pkg/runtimes/docker/network.go, pkg/runtimes/docker/node.go, pkg/runtimes/docker/translate.go, pkg/runtimes/docker/volume.go, pkg/runtimes/runtime.go, pkg/tools/tools.go
- package cluster: use context.Context as first function param in every
exported function
- package cmd: pass cmd.Context() to calls to package cluster exported
functions
- overall: pass context all the way down to the runtime
- createCluster: also wait for master-loadbalancer to be ready (because it makes sense and because we were running in early context cancellation)
=> [Enhancement] v3/overall: use context.Context in top-level exported functions

pkg/cluster/cluster.go, pkg/cluster/loadbalancer.go, pkg/cluster/node.go
nodes and uses it to update the loadbalancer
config when removing a master node
=> [Enhancement] Update loadbalancer if handling master nodes

cmd/create/createNode.go, docs/usage/commands.md, pkg/cluster/cluster.go, pkg/cluster/node.go, pkg/types/types.go, tests/test_full_lifecycle.sh
- new struct: createNodeOpts for wait and timeout values
- new commands for creating/adding multiple nodes which then wait for
all nodes to be up, if specified
- tests/e2e: new test for adding a master node
=> [Enhancement] createNode: add --wait and --timeout flags

cmd/get/getCluster.go, cmd/get/getNode.go, tests/common.sh, tests/test_basic.sh
- no name: get all
- one or more name: get only named nodes/clusters
=> [Enhancement] get: allow multiple or no names for getCluster/getNodes

cmd/create/createCluster.go, docs/usage/commands.md
Introduces a new `--switch` flag for the `create cluster` command.
It automatically switches the default kubeconfig's `current-context` to the new cluster's context.
Works similar to `get kubeconfig --switch`
=> [Feature] create cluster --switch

cmd/create/createCluster.go, cmd/util/ports.go, tests/test_basic.sh
If no `--api-port` was specified or it's set to `random`, we will now try to get a random free port from the OS/Kernel and use that one. If this fails, we'll fallback to the default (6443), just to at least have a chance.
Benefits:
`k3d create cluster one && k3d create cluster two` works without having to worry about choosing free ports to avoid port collisions.
=> [Feature] Choose random API Port by default

cmd/create/createCluster.go, cmd/delete/deleteCluster.go, cmd/get/getKubeconfig.go, docs/index.md, docs/internals/defaults.md, docs/usage/commands.md, docs/usage/guides/exposing_services.md, docs/usage/kubeconfig.md, tests/common.sh
This PR introduces some new CLI defaults when it comes to handling kubeconfigs:
- `k3d create cluster`: does not do anything with kubeconfigs
- `k3d create cluster --update-default-kubeconfig`: merges the new cluster's kubeconfig with the default kubeconfig
- `k3d create cluster --switch-context`: as above + set current-context to new cluster's context
- `k3d get kubeconfig mycluster`: writes `mycluster`'s kubeconfig to `$HOME/.k3d/kubeconfig-mycluster.yaml` and returns the path
- `k3d get kubeconfig mycluster --merge-default-kubeconfig`: merges with the default kubeconfig
- `k3d get kubeconfig mycluster --merge-default-kubeconfig --switch-context` as above + switch current-context
- `k3d get kubeconfig mycluster --output FILE`: write/merge to/with FILE
=> [Enhancement] New kubeconfig defaults

cmd/create/createNode.go, cmd/delete/deleteCluster.go, cmd/get/getKubeconfig.go, cmd/start/startCluster.go, cmd/stop/stopCluster.go
- use by default whereever clustername is required as an arg (if
nArgs is 0)
- use by default whereever clustername is expected as flag
Fixes #291
=> [Enhancement] Sane usage of the default cluster name

pkg/runtimes/docker/container.go
See: https://github.com/moby/moby/issues/29997
It is possible to find a leading '/' in the name from docker runtime.  This handles the possible presence.
=> Handle leading '/' in names for docker runtime

cmd/cluster/clusterList.go, cmd/node/nodeList.go, pkg/runtimes/docker/node.go, pkg/runtimes/docker/translate.go, pkg/types/types.go
This PR introduces a new node field called `State` which includes a boolean parameter `Running` which indicates if the node is up and running as well as a string value `State` which holds the state string representation (1:1 from docker).
With this, there are two UX improvements:
- `k3d cluster list` now shows how many of the nodes are running
```bash
$ k3d cluster create --agents 3
...
$ k3d node stop k3d-k3s-default-agent-1
...
$ k3d cluster list 
NAME          SERVERS   AGENTS   LOADBALANCER
k3s-default   1/1       2/3      true
```
- `k3d node list` now shows an additional `Status` column
```bash
$ k3d node list    
NAME                       ROLE           CLUSTER       STATUS
k3d-k3s-default-agent-0    agent          k3s-default   running
k3d-k3s-default-agent-1    agent …
```
=> [Feature] Node Status

cmd/root.go, cmd/util/plugins.go
This PR is highly inspired by the kubectl plugin system.
When you try to run a subcommand which is not part of the default k3d command tree, k3d will try to find an executable with that name in your `PATH` and execute it (based on the longest possible prefix).
Example:
- `k3d test-plugin`
- executable must be in PATH and named `k3d-test_plugin`
- build k3d from this PR branch
- grab a test-plugin executable (https://github.com/iwilltry42/k3d-test-plugin/releases/tag/v0.0.1) and drop it in your `PATH` (make sure it's executable
- run `k3d test-plugin`
- sub-goal of #304 (callables only)
=> [Feature] Basic Plugin System - SubGoal: callables

cmd/cluster/clusterCreate.go, cmd/util/labels.go
Some service discovery systems are using docker labels to configure DNS, load-balancing, monitoring, metering ... (ie. [dalidock](https://github.com/lionelnicolas/dalidock) , [traefik](https://docs.traefik.io/providers/docker/#routing-configuration), prometheus ...).
This introduce ability to set arbitrary container labels for nodes using a new `--label` parameter to `k3s cluster create`, and supports node filters as is already done for `--volume` and `--port`.
This PR is a port of that feature which already exists in `k3d` v1 (see https://github.com/rancher/k3d/pull/163)
=> add ability to set container labels on nodes using --label/-l

docs/usage/guides/.pages, docs/usage/guides/cuda.md, docs/usage/guides/cuda/Dockerfile, docs/usage/guides/cuda/build.sh, docs/usage/guides/cuda/config.toml.tmpl, docs/usage/guides/cuda/cuda-vector-add.yaml, docs/usage/guides/cuda/gpu.yaml
Adds a guide on how to run CUDA workloads on a customized K3S container.
k3d needs a flag to pass through the gpus when creating the docker container.
#311
=> [Enhancement] Docs: Add guide for CUDA support

docs/usage/guides/exposing_services.md
The API version ```extensions/v1beta1``` is deprecated. 
```
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```
=> [Enhancement] Docs: Use current API version

pkg/cluster/cluster.go, pkg/runtimes/docker/machine.go
This PR adds back some functionality that we already had in v1.x: Using the docker machine IP to expose the Kubernetes API.
This is useful on systems that make use of a VM to run docker.
The enhanced version of the code tries
- `docker-machine ip`
- host lookup for `host.docker.internal`
to get the correct IP that is also routable from the host system.
Fixes #388
Test Builds: https://drive.google.com/drive/u/0/folders/15qbCUY5Uo-FoKFSUXaRqY_sh0j0cmbPm
=> [Feature] clusterCreate: use docker VM IP for API connection

install.sh
At least with bash 5.0.18, GNU Wget 1.20.3 and GNU Awk 5.1.0 the wget installation methods fails because the awk regex does not match the location header. In these versions, instead of `/^  Location:...` it must be `/^Location:...`. In order to retain compatibility with other versions having a different behavior, I changed it to `/^\s*Location:...`.
```
bash-5.0$ wget https://github.com/rancher/k3d/releases/latest --server-response -O /dev/null 2>&1 | awk '/^  Location: /{DEST=$2} END{ print DEST}'
bash-5.0$ wget https://github.com/rancher/k3d/releases/latest --server-response -O /dev/null 2>&1 | awk '/^Location: /{DEST=$2} END{ print DEST}'
https://github.com/rancher/k3d/releases/tag/v3.3.0
bash-5.0$ wget https://github.com/rancher/k3d/releases/latest --server-response -O /dev/null 2>&1 …
```
=> Fix install.sh script if curl is not present

cmd/cluster/clusterList.go, go.mod, pkg/types/types.go, vendor/modules.txt
This adds a `--ouput` flag to `cluster list` for dumping the list of clusters as a JSON or YAML document.
For example, for YAML (with `k3d cluster list -o yaml --token`):
```yaml
- cluster:
name: k3s-default
network:
name: 96eedd1892479898fa6770ba44f49722d0b3fed7a11d0c70f7afb9db672d52c1
external: false
cluster_token: SJbxdPAfVZAlhvYthoHh
nodes:
- name: k3d-k3s-default-serverlb
role: loadbalancer
image: sha256:1a80a007dbdf22e9361de963b5f7c988f87562be86ceaf8820eca9757a9f6d2a
volumes: []
env:
- K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
cmd: []
extra_args: []
port_mappings:
- 0.0.0.0:41751:6443/tcp
restart: true
labels:
k3d.cluster: k3s-default
k3d.role: loadbalancer
network: k3d-k3s-default
extrahosts: []
server_opts:
is_initializing_server: false
exposeapi:
host: ""
host_ip: ""
port: "" …
```
=> [Feature] Options for formatted output of `cluster list` (#416, @inercia))

cmd/util/filter.go, tests/test_basic.sh
- literal @s can now be escaped with a preceding backslash
- use case e.g. `--env HTTPS_PROXY=user:pass\@myproxy.com`
- if the last char before a non-literal @ (designating a following
nodefilter) is a backslash, then it can be escaped with another
backslash (no cascading escapes though)
Fixes #420
=> [Fix] Allow literal @ in flags that have nodefilters

Makefile, cmd/cluster/clusterCreate.go, cmd/registry/registryCreate.go, cmd/util/ports.go, pkg/client/cluster.go, pkg/client/node.go, pkg/client/registry.go, pkg/config/config_test.go, pkg/config/test_assets/config_test_simple.yaml, pkg/config/transform.go, pkg/config/v1alpha1/types.go, pkg/config/validate.go, pkg/runtimes/docker/translate.go, pkg/runtimes/docker/translate_test.go, pkg/types/types.go, pkg/util/ports.go, tests/dind.sh
Switch from basic string representations (80:80/tcp) to real struct (nat.PortMap) representations of ports in all structs.
This will allow us to more easily use the various port mappings internally.
The SimpleConfig type still has a more "human-friendly" representation.
=> [Refactoring/Preparation] use real port structs as prep for registries

pkg/runtimes/docker/translate.go, pkg/types/types.go
Added a new `created` field that exports the creation time for all the containers in the cluster.
=> Print the creation time for containers

cmd/cluster/clusterDelete.go, docs/usage/guides/registries.md, pkg/client/cluster.go, pkg/config/transform.go, pkg/runtimes/containerd/node.go, pkg/runtimes/docker/network.go, pkg/runtimes/docker/node.go, pkg/runtimes/docker/translate.go, pkg/runtimes/docker/volume.go, pkg/runtimes/errors/errors.go, pkg/runtimes/runtime.go, pkg/util/filter.go, version/version.go
This comes with several fixes/improvements
- only consider containers that have the default object label (app=k3d)
- handle network deletion
- check if there are other k3d containers connected
- if there are only registries, disconnect them
- if there are non-registry nodes, leave everything as it is
- if there are any containers connected, that are not automatically
disconnected, log a warning and continue
=> [Enhancement] clusterDelete: proper node and network handling

README.md, docs/index.md
Added k3d Chocolatey package installation option. Chocolatey is a package manager for Windows. An automated package pipeline is setup that will automatically update the package when there is a new k3d "stable" GitHub release published.  In the readme.md "shields" (and also links to the package) is added to reflect the version of the published k3d choco package.
=> [DOCS] Add Chocolatey install option

cmd/node/nodeList.go, cmd/registry/registryList.go, cmd/util/listings.go
* Function for listing nodes in a flexible way, used by the registries and nodes listing commands.
* New `--output=json/yaml` for printing theses listings as YAML/JSON.
=> [Enhancement] Improved listings for nodes & registries (#439, @inercia)

pkg/client/cluster.go, pkg/client/registry.go, pkg/client/registry_test.go, pkg/types/types.go
- LocalRegistryHostingConfigMap
- use localhost or docker-machine as external host IP
- fromContainerRuntime: user container-name + internal port
- registries.yaml: set up mirrors for both external and internal address
Fixes #449
=> [Fix] registry: adjustments on how the registry is perceived

.drone.yml, CHANGELOG.md, Dockerfile, Makefile, cmd/node/nodeCreate.go, cmd/root.go, pkg/client/cluster.go, pkg/client/node.go, pkg/runtimes/docker/container.go, pkg/runtimes/docker/node.go, pkg/runtimes/docker/util.go, pkg/types/types.go, tests/assets/config_test_simple.yaml, tests/common.sh, tests/dind.sh, tests/extra_test_k3s_versions.sh, tests/runner.sh, tests/test_basic.sh, tests/test_config_file.sh, tests/test_full_lifecycle.sh, tests/test_multi_master.sh, tests/test_multi_master_start_stop.sh, tests/test_registry.sh
This PR contains some fixes:
- Fixes #452 : caused by etcd and leader election, fixed by doing sequential ordered restart of servers
- also adds e2e test for it
- Fixes adding nodes by resetting the new node's status to not be the same as the one it was copied from
=> [Fix] Properly restart clusters with more than one server (sequential ordered start)

cmd/cluster/clusterCreate.go
=> Fix for KubeAPI Port assignment when using config files (#490, @dtomasi)

docs/usage/multiserver.md
See this issue: #315. In resource constrained environments, starting k3d with more than one servers fails.
Document the minimal requirements. They are based of empirical research documented [here](https://github.com/rancher/k3d/issues/315#issuecomment-700521779)
- While this is probably the most effort/reward effective way of solving this, "fix-by-documenting" is not really a profound solution. If there are better ideas, pleas share.
- The estimates of the minimal requirements are as good as I can judge. If more elaborate ways of measuring them are known, please share too.
Issue #315.
=> State minimal recommended specs for multi-server (#481, @Filius-Patris)

pkg/runtimes/docker/network.go, pkg/runtimes/docker/util.go
closes #485 
Two clusters are created in `k3d-action-bridge-network`. Registry is successfully attached to both of them.
```json
[
{
"Name": "k3d-action-bridge-network",
"Id": "63f11e509c49dd2ccbc44459981c5c81f353a1840a6dd9f2a0c7374de71a9cb6",
"Created": "2021-02-08T13:36:09.5304736Z",
"Scope": "local",
"Driver": "bridge",
"EnableIPv6": false,
"IPAM": {
"Driver": "default",
"Options": null,
"Config": [
{
"Subnet": "192.168.32.0/20",
"Gateway": "192.168.32.1"
}
]
},
"Internal": false,
"Attachable": false,
"Ingress": false,
"ConfigFrom": {
"Network": ""
},
"ConfigOnly": false,
"Containers": {
"3a5cd4b100725ac325d3a62f7b9ef5ec6eaae912617d20e3e5e1d9da8a64c52c": {
"Name": "k3d-test-gslb2-agent-1",
"EndpointID": "4271a93479eba501478bbf49261096e606b0915a5843153fca03ff00c461b20d",
"MacAddress": …
```
=> [Fix] Reuse registry in multicluster (fixes #485,@kuritka) (#486, @kuritka)

cmd/cluster/clusterStop.go
I noticed the `k3d cluster stop` help has what looks like a miss when coping and pasting. So I fixed the typo.
Simple typo fix in the `k3d cluster stop` help docs.
Because knowledge is power!
The help documentation will correctly represent what the `--all` flag does.
=> Fix typo in cluster stop command doc (#513, @searsaw)

cmd/registry/registryList.go
Add status column to registry list:
```
NAME                  ROLE       CLUSTER
k3d-local.localhost   registry
```
:arrow_down: 
```
NAME                  ROLE       CLUSTER   STATUS
k3d-local.localhost   registry             running
```
I wanted to see the status column as I often stop the registry containers manually when I'm not using `k3d`. Also there was already a TODO comment for this.
=> [Enhancement] Add status column to registry list

Makefile
Go 1.16 supports the darwin/arm64 build target.. let's build for it :building_construction:
=> [Enhancement] build: add darwin/arm64 (Silicon, M1) build target

pkg/config/transform.go
Fixing a behavior where Host option is always used when generating kubeconfigs, even when a HostIP is provided.
#499 
The logic of generating the kubeconfig has changed is not always based on the Host field, assume this is OK when a HostIP is specified (and no Host) to use this field for the server part of the kubeconfig.
=> [FIX] Properly handle host/hostIP cases for kubeconfig (#500, @fabricev)

docs/usage/.pages, docs/usage/configfile.md
Add some documentation on config file support.
=> [Enhancement] docs: add page about the config file

README.md
Adds instructions on how to install `k3d` via MacPorts.
Additional methods for installing on macOS.
=> README: instructions for installing via MacPorts

cmd/root.go, pkg/runtimes/docker/info.go, pkg/runtimes/runtime.go, pkg/runtimes/types/types.go
This PR adds the `Info()` function to the Runtime interface which populates and returns a `RuntimeInfo` struct which can be used in the future to add runtime-specific configurations (like `/dev/mapper` mounts for zfs/btrfs or cgroup version specifics, etc.).
This also adds the `k3d runtime-info` command (hidden) that can be used to gain debug information.
Example:
`$ k3d runtime-info`
```yaml
name: docker
endpoint: /var/run/docker.sock
version: 20.10.5
ostype: linux
os: Pop!_OS 20.10
arch: x86_64
cgroupversion: "1"
cgroupdriver: cgroupfs
filesystem: extfs
```
=> [Feature] Runtime Info

cmd/cluster/clusterCreate.go
#569 
Change the `k3d cluster create --help` usage example info.
The contents of Example cannot be used to initialize the cluster:
- `-l, --label` 
- `-e, --env`
=> fix create command's flags typo (#568, @Jason-ZW)

CHANGELOG.md, cmd/root.go, pkg/client/cluster.go, pkg/runtimes/docker/translate.go, pkg/runtimes/docker/translate_test.go, pkg/runtimes/docker/util.go, pkg/runtimes/runtime.go, pkg/types/fixes/assets/cgroupv2-entrypoint.sh, pkg/types/fixes/fixes.go
Cgroupv2 fix as per https://github.com/k3s-io/k3s/pull/3237 & https://github.com/k3s-io/k3s/pull/3242
Activate by setting env `K3D_FIX_CGROUPV2` to `1` or `true`.
This will override the entrypoint of the k3s containers with the script that fixes cgroupv2 support as per the linked PRs.
- #493
=> fix/workaround: add workaround for cgroupv2 until fixed in k3s

pkg/client/node.go, pkg/runtimes/docker/util.go, pkg/runtimes/errors/errors.go, pkg/runtimes/runtime.go
Nodes created via `k3d node create ...` now inherit the registry configuration file from the chosen existing node (if there is any).
Fixes #595
=> [FIX/ENHANCEMENT] node/create: inherit registry config from existing nodes

pkg/client/cluster.go, pkg/client/fixes.go, pkg/client/node.go
This PR enables the custom not-so-experimental-anymore entrypoint script for servers/agents if k3d detects that the runtime is on CgroupsV2.
This can be disabled by setting the environment variable `K3D_FIX_CGROUPV2=false`.
Additionally, the fix is now active also for `k3d node create`, not only for `k3d cluster create`.
Fixes #599
=> [Feature] cgroupv2fix: enable by default and move to nodestart

pkg/client/kubeconfig.go
when first create kubeconfig file on windows, if the handle of empty file not close, will cause `Access Deined` on the follow step `os.Rename`
=> new file handle should close after create (#628, @dragonflylee)

pkg/client/node.go
- nodewaitforlogmessage: drop subsecond precision
- it looks like this caused the issue due to rounding to the next full second, which may be already after the target log message appeared
- log the logs that we see in `nodeWaitForLogMessage` per role selected via env var `K3D_LOG_NODE_WAIT_LOGS`, e.g. `K3D_LOG_NODE_WAIT_LOGS=loadbalancer,agent` to see them for the serverlb and agent nodes
- fixes #592
- fixes #621
=> [FIX] waiting for serverlb logs that exist already

CHANGELOG.md, cmd/node/nodeCreate.go, cmd/node/nodeDelete.go, pkg/client/loadbalancer.go, pkg/client/node.go
=> [Cleanup] Follow-Up for #638

CHANGELOG.md, cmd/cluster/clusterCreate.go, tests/assets/config_test_simple.yaml
E.g. `$HOME` -> `/home/iwilltry42`
This is done unconditionally/unchecked and even before viper reads in the config and before the file gets validated using the JSONSchema.
That way, we don't have to include much logic and the user has the most freedom possible here.
Fixes #537
=> [FEATURE] Expand environment variables in the config file

pkg/runtimes/docker/network.go
If there is no default gateway in the bridge network, k3d crashes because it tries to parse the empty gateway string. This PR will use the default gateway if the gateway does not exist. A cluster can be created than.
For some time docker does not create an automatic gateway in case I create a new network. When I create a bridge network without a gateway and try to connect it to k3d, the cluster installation of the latest versions of k3d crashes.
For example, this won't work for me:
```shell
docker network create my-network --subnet=172.18.0.0/16
k3d cluster create my-cluster --network=my-network
```
```json
"IPAM": {
"Driver": "default",
"Options": {},
"Config": [
{
"Subnet": "172.18.0.0/16"
}
]
},
```
Right now we have to do something like this manually:
```shell
docker network create …
```
=> [Fix] Use default gateway, when bridge network doesn't have it (#666, @kuritka)

cmd/image/imageImport.go, docs/usage/commands/k3d_image_import.md, pkg/tools/tools.go, pkg/tools/tools_test.go
Once upon a time, all Docker images were stored either locally or on Docker Hub. They were called `repoName/imageName:versionName` and all was well.
Then people started to build other registries. Eventually it was decided that the registry will just be prefixed to the image name: `registry-name.example/repoName/imageName:versionName`. But to maintain compatibility, images without a registry prefix were still fetched from Docker Hub, the default registry.
The Docker Hub registry eventually was named `docker.io` and images that were tagged `docker.io/repoName/imageName:versionName` were equivalent to images tagged as `repoName/imageName:versionName`.
Probably on a different occasion and for different reaons, `latest` would be assumed by Docker if no `versionName` part was given.
These two …
=> [Enhancement] Follow Docker's image nameing convention in `k3d image import` (#653, @cimnine)

cmd/image/imageImport.go, pkg/tools/tools.go, pkg/types/types.go
Title says it all..
- if there's a tools node container, but it's not running start it, then re-use it
- new `k3d image import [-t | --keep-tools]` flag to not delete the tools node after importing the image (so it can be re-used in the next round of imports)
Potentially fixes #671
=> [ENHANCEMENT] imageImport: start existing tools node before using it and add option to keep it around

install.sh
Fixes macOS on M1 execution of `./install.sh`
```zsh
curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
No prebuilt binary for darwin-arm64.
To build from source, go to https://github.com/rancher/k3d
Failed to install k3d
For support, go to https://github.com/rancher/k3d.
```
Does not affect existing functionality of actual CLI
=> Add darwin-arm64 to supported install.sh archs

docgen/main.go, pkg/client/cluster.go, tools/cmd/image.go, tools/main.go
- Branch: `main-v5`
- Commit: `60738205`
- Time: `k3d cluster create testspeed -s 3 -a 3  0.87s user 0.54s system 1% cpu 1:23.85 total`
- Branch: `enhancement/concurrent-worker-creation`
- Commit: `9d63c3b3`
- Time: `k3d cluster create testspeed -s 3 -a 3  1.24s user 0.42s system 2% cpu 1:03.23 total`
... resulting in a 20 seconds improvement in overall cluster creation time
This didn't use a super clean test setup, so don't take the "result" 100% for granted.
Fixes #673
=> [Enhancement] Create workers/helpers concurrently

README.md, docs/index.md
the current command errors with:
```
$ go install github.com/rancher/k3d
go install: version is required when current directory is not in a module
Try 'go install github.com/rancher/k3d@latest' to install the latest version
```
=> docs: fix go install command

cmd/cluster/clusterCreate.go
When only hostIP is provided then only generate random port instead of overriding hostIP.
Closes: #692
=> [FIX] Do not override hostIP when hostPort is missing (#693, @lukaszo)

.drone.yml, Dockerfile, dind-manifest.tmpl, manifest.tmpl, proxy/manifest.tmpl, tools/manifest.tmpl
Fixes #694
Now the pipeline should build/tag/push images/manifests like follows:
<table>
<tr>
<td>Git Event
<td>Git Tag
<td>Target Branch
<td>Resulting Tags
<tr>
<td>tag
<td>v5.1.0 (release)
<td>*
<td>5, 5.1, 5.1.0 (manifest + images with `-OS-ARCH` suffix)
<tr>
<td>tag
<td>v5.1.0-dev.1 (pre-release)
<td>*
<td>5.1.0-dev.1 (manifest + images with suffix)
<tr>
<td>push
<td>---
<td>main
<td>latest (manifest + images with suffix)
<tr>
<td>push
<td>---
<td>* (not main)
<td>---
</table>
Images:
- `rancher/k3d`: `rancher/k3d:<tag>` & `rancher/k3d:<tag>-dind` <-- now also multiarch
- `rancher/k3d-proxy`
- `rancher/k3d-tools`
=> [Enhancement] Improved Pipeline for Multiarch Images and SemVer Tags

pkg/tools/tools.go, pkg/tools/tools_test.go
Unfortunately, the PR https://github.com/rancher/k3d/pull/653 broke the `k3d image import` command. Since then, you can import only the first found image due to `break` instead of `continue` statement in `for` loop.
This PR fixes that bug and adds test coverage to avoid regression in the future. 
Fix https://github.com/rancher/k3d/issues/700
None
=> [FIX]: import all requested images (#701, @mszostok)

cmd/cluster/clusterCreate.go, docs/usage/configfile.md, go.mod, pkg/client/cluster.go, pkg/config/process.go, pkg/config/process_test.go, pkg/config/transform.go, pkg/config/v1alpha3/schema.json, pkg/config/v1alpha3/types.go, pkg/runtimes/docker/network.go, pkg/runtimes/docker/translate.go, pkg/types/types.go
This PR changes several parts related to actions k3d is taking to modify DNS in k3d managed clusters.
Here's an excerpt:
- remove`--no-hostip` flag and the related `disableHostIPInjection` config option
- inject host IP on every cluster startup (except when hostnetwork is chosen)
- this includes an entry in `/etc/hosts` and in the CoreDNS configmap
- fixes #401 
- inject host entries for every cluster network member container into the CoreDNS configmap
- fixes #522
=> [Enhancement] DNS Injection

cmd/image/imageImport.go, pkg/client/cluster.go, pkg/client/environment.go, pkg/client/host.go, pkg/client/node.go, pkg/client/registry.go, pkg/client/tools.go, pkg/client/tools_test.go, pkg/runtimes/docker/network.go, pkg/runtimes/docker/translate.go, pkg/runtimes/docker/translate_test.go, pkg/types/fixes/assets/k3d-entrypoint-cgroupv2.sh, pkg/types/fixes/assets/k3d-entrypoint-dns.sh, pkg/types/fixes/assets/k3d-entrypoint.sh, pkg/types/fixes/fixes.go, pkg/types/types.go
DNS 'n' Stuff
- before starting the cluster, gather environment info via tools node
- use hostIP/gatewayIP for DNS (iptables + resolv.conf updated in entrypoint script)
- revamp of custom entrypoint scripts
To-Do
- tested via `service docker restart` and checking new log files (created by the entrypoint script with timestamps)
This potentially fixes #209
=> [Enhancement] Network Magic

cmd/cluster/clusterCreate.go, cmd/cluster/clusterDelete.go, cmd/util/config/config.go, tests/test_config_file.sh
- move viper initialization from k3d config file to separate util
sub-package in cmd/
- use that new subpackage init function to leverage the config file in
`k3d cluster delete` -> the delete function only cares about the `name` of the cluster and does not check anything else in the config file!
- cover that with an e2e test case
fixes  https://github.com/rancher/k3d/issues/715
=> [Feature] Spread config file usage in CLI: `k3d cluster delete --config myconfig.yaml`

cmd/node/nodeCreate.go, pkg/client/cluster.go, pkg/client/node.go, pkg/client/tools.go, pkg/runtimes/docker/network.go, pkg/runtimes/docker/node.go, pkg/types/node.go, pkg/types/types.go
- `--cluster` flag parsed for `https://` prefix and node creation treated differently accordingly
- new `--network` string array flag to add the node to multiple networks (primary network when adding to a remote cluster)
- new `--token` flag to provide the cluster token
Note: currently this is very simple, as it e.g. does not check for special cases like when someone overrides the "reserved" K3s environment variables (`K3S_URL`, `K3S_TOKEN` and `K3S_KUBECONFIG_OUTPUT`).
Those will be specified via the `--cluster` and `--token` flags only.
Note2: `--network` is required when connecting to a cluster running in a different docker network, as the node has to join that network for communication to work.
```bash
k3d cluster create simremote
apiport=$(docker inspect k3d-simremote-server-0 …
```
=> [Feature] CreateNode: add token and network flags and allow remote cluster

cmd/cluster/clusterCreate.go, pkg/client/cluster.go, pkg/client/loadbalancer.go, pkg/config/transform.go, pkg/config/v1alpha3/types.go, pkg/types/loadbalancer.go, proxy/templates/nginx.tmpl
- allow overriding k3d-proxy settings (workerProcesses,
defaultProxyTimeout) via CLI `--lb-config-override` stringslice flag (see example)
- add new field to loadbalancer config and SimpleConfig structs
```bash
k3d cluster create testlbconfig --lb-config-override "settings.defaultProxyTimeout=300" --lb-config-override "settings.workerProcesses=2048"
```
results in the following loadbalancer config (`docker logs k3d-testlbconfig-serverlb`):
```bash
===== Initial nginx configuration =====
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
###################################
###################################
error_log stderr notice;
worker_processes auto;
events {
multi_accept on;
use epoll;
worker_connections …
```
=> [Feature] Loadbalancer config overrides

cmd/cluster/clusterCreate.go, docs/usage/configfile.md, docs/usage/guides/registries.md, pkg/config/config_test.go, pkg/config/test_assets/config_test_registries.yaml, pkg/config/transform.go, pkg/config/v1alpha3/migrations.go, pkg/config/v1alpha3/schema.json, pkg/config/v1alpha3/types.go, pkg/runtimes/docker/network.go, tests/assets/config_test_simple.yaml, tests/assets/config_test_simple_migration_v1alpha3.yaml, tests/test_config_file.sh, tests/test_config_with_overrides.sh, tests/test_registry.sh
Open question: since the current `--registry-create` flag is a boolean type flag, converting it to a string flag that takes some config string, would break backwards compatibility.
This could be more or less ok though since it's planned for the the v5 major release that contains quite a few breaking changes.
Let's get some opinion on this:
- :one: (Vote :+1:) Keep `--registry-create` and add additional `--registry-create-override "NAME:HOST:HOSTPORT"` (setting this would infer `--registry-create`, while only `--registry-create` would set the defaults for name, host and hostport)
- :two: (Vote :heart:) convert `--registry-create` bool flag to string flag `--registry-create "NAME:HOST:HOSTPORT"`, which breaks backwards compatibility, but keeps the CLI cleaner.
Please vote by reacting to …
=> [Enhancement] More powerful registry-create opt

pkg/client/cluster.go, pkg/client/environment.go, pkg/client/host.go, pkg/client/tools.go, pkg/runtimes/docker/host.go, pkg/types/types.go, tools/Dockerfile
- make use of environment and runtime info
- DfD: use host.docker.internal
- All other cases: use Docker network Gateway
- k3d-tools: based on alpine to have `getent` present
=> [Enhancement/Fix] Properly use env/runtime info and inject dns accordingly

pkg/client/cluster.go, pkg/client/environment.go, pkg/client/node.go, pkg/runtimes/docker/container.go, pkg/runtimes/docker/translate.go
- do not try to get host gateway IP via tools node or network inspect
- do not try to inject host.k3d.internal into /etc/hosts
- do not try to inject host.k3d.internal into CoreDNS configmap
- when getting node info from container, do not try to get IP info
- fixes #842
=> fix: do not do any network magic when using hostnetwork

docs/usage/.pages, docs/usage/k3s.md
Adds some documentation on K3s built-in features/services including `local-path-provisioner`, `servicelb`, `traefik` and `coredns`
fixes #795
=> docs: add documentation on k3s features

cmd/cluster/clusterCreate.go, pkg/config/process.go
=> [FIX] clusterCreate: process simpleConfig before validation step to avoid early exit in hostnetwork mode

pkg/client/host.go, pkg/client/tools.go, pkg/runtimes/docker/docker.go, pkg/runtimes/docker/node.go, pkg/runtimes/docker/util.go, pkg/types/types.go
- do not close connection of exec process before having read everything
- as a backwards-compatible fix, we now read all logs into a new
bufio.Reader so we can savely close the connection and original reader
- start tools node with --add-host=host.k3d.internal:host-gateway
(docker feature) and use it for getHostIP on DfD (TODO: we can use this
on all platforms)
- Problem: e.g. in WSL2, all of the above conditions are true, but `host.docker.internal` is not reachable
- Pinging it with a library would draw in unnecessary dependencies
- As an alternative check, we just look if the `WSL_DISTRO_NAME` env var is present to determine if k3d is running in WSL2 and if so, we do not use host.docker.internal
- fixes #858 (both problems)
=> [FIX] getHostIP: fix failing on DfD and init new host.k3d.internal injection

cmd/registry/registryCreate.go, cmd/util/ports.go, pkg/client/cluster.go, pkg/client/node.go, pkg/runtimes/docker/docker.go
fixes #876 
- move docker-machine lookup into general GetHost function
- only use GetHost result if API host is default (0.0.0.0) to not override user-provided value
- when looking up IP for host value (e.g. localhost), only use IPv4 to prevent errors
=> [Fix] only replace default api host with docker host

pkg/client/tools.go
Closes #878 
Fixes the problem by separately loading tars one by one when loading with streams instead of concatenating.
To be honest, at this point i'm not _exactly_ sure but from my debugging it seems like some EOF marker in the tar causes `ctr` to stop reading and exit, causing the exec stream to close and the load to error out when multiple tar files are passed in the arguments
For some reason this doesn't happen with streams from the docker engine (possibly because it properly concatenates the tar streams but this seems like pretty low-level stuff)
It might have some minor performance impact, but it doesn't seem to make much of a difference in my quick tests. (starting docker exec streams seems pretty cheap)
=> fix(image-loading): mitigate tar load problem

cmd/cluster/clusterDelete.go
With k3d I can delete a cluster before it is created. Such a use case is very useful in case I want to restart my test environment. 
```Makefile
reset:
k3d cluster delete mycluster
k3d cluster create mycluster
<installing things....>
```
Even better is to use a configuration with the argument `-c config.yaml`. The k3d can delete a 
cluster based on configuration, but it cannot handle the case that the cluster does not exist.
```log
INFO[0000] Using config file ./local.yaml (k3d.io/v1alpha3#simple) 
FATA[0000] failed to delete cluster 'mycluster': No nodes found for given cluster 
```
This PR allows that if I use the configuration and delete a non-existing cluster, k3d will not end up fatal.
```log
INFO[0000] Using config file ./local.yaml (k3d.io/v1alpha3#simple) 
INFO[0000] No nodes …
```
=> [Fix] Removing non-existing cluster via configuration

pkg/config/config.versions.meta.schema.json, pkg/config/config.versions.schema.json, pkg/config/v1alpha2/schema.json, pkg/config/v1alpha3/schema.json
- embed a versions file in the k3d repo that links to the existing config schemas as per https://github.com/SchemaStore/schemastore/pull/2057#issuecomment-1024470105
- inspired by and mostly copied from https://github.com/ory/kratos/blob/master/.schema/version.schema.json :pray:
=> add: schema versions in-repo to link to from schemastore.org

docs/usage/configfile.md, docs/usage/registries.md, pkg/config/config_test.go, pkg/config/jsonschema_test.go, pkg/config/migrate_test.go, pkg/config/test_assets/config_test_registries.yaml, pkg/config/test_assets/config_test_simple.yaml, pkg/config/test_assets/config_test_simple_2.yaml, pkg/config/test_assets/config_test_simple_invalid_servers.yaml, pkg/config/test_assets/config_test_simple_migration_v1alpha4.yaml, pkg/config/types/types.go, pkg/config/v1alpha4/migrations.go, pkg/config/v1alpha4/schema.json, pkg/config/v1alpha4/types.go, tests/assets/config_env.yaml
Move `name` to `metadata.name` in `k3d.io/v1alpha4 Simple` config file format.
Fixes #937 
This change in config format allow users to kustomize cluster-config using `kustomize`.
This is a breaking change in the `v1alpha4` config-format, but this is a new and currently unreleased version.
=> [FEATURE] Config file compatible with Kustomize

pkg/client/cluster.go
fix 2 problems
1. serverlb should restart unless stopped
2. serverLoadBalancer should be created before using in avoid of panic
issue https://github.com/rancher/k3d/issues/947
fix corner case
=> fix: serverlb should be created before using and restarted unless stopped

pkg/client/node.go
Fixed typo.
```
calulated -> calculated
```
=> Fix typo in node.go

cmd/root.go
=> [Feature] add env var LOG_COLORS=[1|true|0|false] to toggle colored log output (enabled by default)

pkg/client/tools.go
=> fix: mutex on ensureToolsNode to avoid duplicate container name causing error

pkg/client/cluster.go
... was preventing cluster startup when CoreDNS is disabled in K3s.
- also cleans up some legacy unused function
- fixes #912
=> [Fix] detect '--disable=coredns' and conditionally disable injection

cmd/root.go
Currently the log level is only set if an error occurs during the
parsing of the LOG_LEVEL environment variable. This logic needs to be
inverted, and the log level set if there is no error.
=> fix: invert logic for LOG_LEVEL parsing

.github/workflows/aur-prerelease.yml, .github/workflows/aur-release.yml, deploy-aur.sh
Relaxing the Arch Linux docker version in the deploy script. In the end we're not depending on specific packages of Arch Linux since we install most of them ourselves. This should prevent builds breaking like it currently does, because of outdated keys or similar.
~~The alternative would be to use sth like `pacman-key --refresh-keys`, but this takes always takes a while...~~
EDIT: I pushed another commit which will update `archlinux-keyring` when the deploy starts, which automatically gets all the latest keys.
Breaking deploy scripts to AUR
-
=> ci/action/arch: Switch from absolute Arch docker version to a more relaxed one

pkg/runtimes/docker/translate.go
Improves compatibility with rootless Podman
Sets the default `NetworkMode` to `bridge`.
- Some users might like to use `k3d` with Podman (See #84)
- Podman currently [defaults](https://github.com/containers/podman/blob/ccb96a2791fe9ae58a697bf1715600ecec8b246b/pkg/specgen/namespaces.go#L355-L359) to `slirp4netns` when running as a rootless service.
- Changing this default behaviour in Podman might break other users of the Podman API.
- Might break usage with runtimes without support for bridge networks (Is this a thing?)
=> fix: Use bridge as the default networking mode

docs/index.md
Add Connect section in main web page.
It is useful to have community related information directly on the website.
It's just documentation.
=> Add Connect section to k3d.io

cmd/root.go, docs/usage/commands/k3d_completion.md
=> fix zsh completion output

install.sh
When invoking the install script, the installation process can fail
silently so that the `k3d` binary includes only the ASCII string 'Not
found'. This can be avoided by passing the `--fail` flag so that the
command fails if a 4XX or 5XX response is received.
This change adds a `scurl` function that invokes `curl` with this flag,
as well as flags that ensure that at least TLS v1.2 is used (this helps
mitigate protocol downgrade attacks).
This is based on the defaults we use in Linkerd. See: https://github.com/linkerd/linkerd2/blob/a0b112471eef7e3975fbc8564df52d83894c3fa3/bin/scurl
=> install.sh: Invoke curl with secure defaults

pkg/runtimes/docker/network.go
=> [FIX] GetGatewayIP for host.k3d.internal should error out if there's no gateway defined

cmd/node/nodeCreate.go
fixes #716
```bash
$ k3d cluster create test -a 1
...
$ k3d node create testnode2 --role agent --cluster test --k3s-arg '--node-label=foo=bar'
...
$ docker inspect k3d-testnode2-0
...
"Cmd": [
"agent",
"--node-label=foo=bar"
],
...
$ k3d node create testnode3 --role agent --cluster test --k3s-arg '--node-label=spam=eggs'
...
$ kubectl get nodes --show-labels                                                                                      
NAME                STATUS   ROLES                  AGE     VERSION        LABELS
k3d-testnode2-0     Ready    <none>                 4m11s   v1.22.7+k3s1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,foo=bar,kubernetes.io/arch=amd64,kubernetes.io/hostname=k3d-testnode2-0,kubernetes.io/os=linux,node.k …
```
=> add: node create --k3s-arg flag

cmd/node/nodeCreate.go, pkg/client/node.go
=> change: no default image for node creation in local cluster where image should be copied from existing nodes

pkg/config/transform.go, pkg/config/v1alpha4/schema.json, pkg/config/v1alpha4/types.go
this PR adds a Image config to simpleConfig.Registry.Create, so we can specify a alternative registry other than "docker.io/library/registry:2"
we're running k3d in our CI infrastructure, but unfortunately runs into an error on rate limitted by docker.io registry:
we can specify a custom `--image` in the `k3d registry create` subcommand which allowing us switch a private registry to avoid this problem, but we do not have a related image config in the `config.yaml` in `k3d cluster create` yet, in our CI config, this config.yaml plays an all-in-one config for k3d, it'd be convenient to allow us config the registry image in this config file.
this PR do not change the existed behavior, if the image field is empty, it falls back to the default registry image.
=> feat: allow set image in simpleConfig.Registries.Create

docs/design/defaults.md
In the document default section, the link to the networking page was not working
https://k3d.io/v5.4.1/design/defaults/#networking
This PR fixes that
=> docs: fix defualts-networking href

cmd/cluster/clusterDelete.go
With the change from using `name` to `metadata.name`, the delete by config file didn't work. This fixes that bug
Fixes #1041
No change to functionality, except a bugfix
=> Fix deleting of cluster by config file

Makefile
Using `go get` for installing binaries/tools is deprecated and it's
littering the local go.mod and vendor.txt files. This change fixes that
by using `go install` instead.
Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>
It changes `go get` usage to `go install` for fetching a binary tool.
Using `go get` for that purpose is deprecated and makes unnecessary changes in go.mod (thinking that you are going to use the mentioned project as a dependency).
There should be no implications for developers using recent Go vesions.
=> make: Use `go install` instead of `go get` for installing tools

docs/usage/advanced/calico.md
This PR adds a note to the docs explaining that you do not need to switch to calico just go get network policy enforcement.
The current wording is a bit confusing. It led me to think that I needed calico (or something else) to be able to enforce network policies.
Slightly clearer docs.
=> Clarify: No need for calico for network policies

docs/usage/advanced/podman.md, pkg/runtimes/docker/network.go
Fix running k3d with podman and cgroups (v2)
* By running podman in rootless mode, `k3d`/`k3s` requires extra delegation in order to work (cpu, cpuset and I/O delegations), added the steps to the doc. Some errors like `failed to find cpu cgroup (v2)` would happened on cgroup v2 and cpu delegation not enabled (https://github.com/k3d-io/k3d/issues/585)
* Podman is API compatible with docker, however there is a slightly difference on network retrieval of IP address. One uses only CIDR notation (127.0.0.1/32) while the other, for unique IP address use the literal notation (127.0.0.1). Create a wrapper function to extract the value instead of throwing an error.
The following happened before the fix (`netaddr.ParseIPPrefix("11.89.1.4"): no '/' `)
```shell
❯ k3d cluster create testing
INFO[0000] …
```
=> Add support to run with podman in rootless mode using cgroups v2

pkg/config/v1alpha4/types.go
Hello everyone, the command `k3d config init` creates a faulty config for cluster creation. This commit moves the `name`   into `metadata.name` for the `k3d.io/v1alpha4 Simple` format as per https://github.com/k3d-io/k3d/pull/945.
=> Fix default config template for v1alpha4

cmd/cluster/clusterCreate.go, cmd/cluster/clusterList.go, cmd/config/configMigrate.go, cmd/debug/debug.go, cmd/root.go, cmd/util/config/config.go, cmd/util/listings.go, pkg/client/cluster.go, pkg/client/loadbalancer.go, pkg/client/node.go, pkg/client/ports.go, pkg/client/registry.go, pkg/config/transform.go, pkg/config/types/types.go, pkg/config/v1alpha2/types.go, pkg/config/v1alpha3/types.go, pkg/config/v1alpha4/types.go, pkg/runtimes/types/types.go, pkg/types/k3s/registry.go, pkg/types/k8s/registry.go, pkg/types/loadbalancer.go, pkg/types/registry.go, pkg/types/types.go, pkg/util/util.go, pkg/util/yaml.go, pkg/util/yaml_test.go
Print consistent output for commands.
Currently, some commands (e.g. `k3d cluster list` or `k3d cluster get`) prints differently per output option (`json` / `yaml`). This behavior may break interoperability and can make users hard to figure out the difference between outputs.
Replace `gopkg.in/yaml.v2` with `sigs.k8s.io/yaml`, which converts the json-encoded struct to yaml.
(`sigs.k8s.io/yaml` is a wrapper for `gopkg.in/yaml.v2` - https://github.com/kubernetes-sigs/yaml/blob/b5bdf49df8aeb9756eee686adc7b4a6b3640bc14/yaml.go#L30-L38)
Commands will print same struct for both `json` / `yaml` output options.
**This change may breaks previous behavior, since this commit removes `yaml` tag from structs.**
I think it would be better to use either `gopkg.in/yaml.v2` or `sigs.k8s.io/yaml` only …
=> fix: print consistent json/yaml output

docs/index.md
Improve markdown code syntax
Improve documentation on SHELL commands
Get the SHELL commands more user-friendly
Only act on formatting, no changes on script contents
=> Beautify bash commands

pkg/client/cluster.go
Fixes #1151
Subsequent `ClusterGet` calls will continue to append existing volumes.
As `ClusterGet` is called twice when running the delete cmd, this causes volumes in the array to be duplicated, which ends up throwing a false warning message.
This change adds a check to `ClusterGet` to ensure that only non appended volumes are added.
=> fix: avoid appending existing volumes

docs/usage/k3s.md
Fixed indentation of the CoreDNS "Resources" section.
As is, It looks like the CoreDNS section doesn't have any content.
None. Doc only.
=> fix: indentation for CoreDNS doc

pkg/runtimes/docker/node.go
Rename an inner error to `logsError` to stop it shadowing the value of a higher scoped `err`.
The assignment from `io.ReadAll` was overwriting the value of the original error and stopping the logs of the failed exec from being printed.
fixes #1171
Now when `k3d image import` fails the logs from the failed command will be logged (this is intended behaviour):
```
$ ../k3d/bin/k3d image import -c local -m direct test.tar
INFO[0000] Importing image(s) into cluster 'local'      
INFO[0000] Importing images from 1 tarball(s)...        
INFO[0000] Importing images '[test.tar]' into node 'k3d-local-server-0'... 
ERRO[0001] Failed to import image(s) into cluster 'local': could not load image to cluster from stream test.tar: error loading image to cluster, first error: failed to import images in …
```
=> fix: logs error shadowing exec error

cmd/cluster/clusterCreate.go
Add closing backtick to example command for k3s-arg flag
This makes the documentation consistent
No changes to existing behavior
=> docs: Add missing backtick to k3s-arg example command

cmd/cluster/clusterCreate.go, cmd/util/config/config.go
=> Support reading in registries-config via env

go.mod, pkg/client/tools.go
In Darwin/arm64 platform, k3d can not correctly import image to cluster. In this PR, I add `--all-platforms` arguments for `ctr image import` to fix it.
It is an essential function for k3d. We should fix the bug. Related issues: https://github.com/k3d-io/k3d/issues/954, https://github.com/k3d-io/k3d/issues/1072
=> Fix: unable to import image Darwin/arm64

Makefile
Generate the release  sha256 checksum file for k3d binaries 
#1208 , helping to verify the binaries
@all-contributors please add @kameshsampath  for code
=> fix: generate checksum for k3d binaries

pkg/client/cluster.go, pkg/client/node.go, pkg/types/types.go, tests/local_test_registration_using_server_lb.sh
This PR changes the K3S_URL env value which defaults to server-0 to whichever server is available instead.
See #1189 
It changes the way node create command sets the `K3S_URL` value.
=> change: Use loadbalancer or any *active* server as K3S_URL

version/version.go, version/version_test.go
Better handling of http call made to update.k3s.io.
Update the way of handling the http client call for fetchLatestK3sVersion, to make it more testable.
#1129 
This will check the http status code to the calls made to update.k3s.io, and handle it accordingly.
=> fix: improved error handling when update.k3s.io returns a 5XX or invalid response

.github/workflows/test-install-osmatrix.yaml, install.sh
Fix install.sh script for windows (mingw/msys2 bash).
The install script wasn't working on windows b/c the released binary for windows has a .exe extension on it which made the script error with a 404. Also, the USE_SUDO variable should be set to false by default on windows (otherwise piping script to bash won't work). 
An alternative fix would be to change the releases to not include the .exe extension on the windows binary but maybe that was done for use outside of mingw where the install.sh script wouldn't be used. The install script still saves k3d to /usr/local/bin/k3d without the .exe extension and it works without the .exe extension (in msys2/mingw). It would work the same way if it was saved as k3d.exe.
=> fix: install script on windows

docs/usage/advanced/podman.md
Update [podman documentation](https://k3d.io/v5.4.1/usage/advanced/podman/)
Add network creation.
Update examples of manaully starting podman socket to start as a background job.
Tested with podman version
```bash
podman version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 15:01:27 2022
OS/Arch:      linux/amd64
```
The current documentation doesn't work due to podman's default `podman` network lacking dns. Node's fail to resolve other node names during installation/initialization.
```bash
podman network inspect podman -f '{{ .DNSEnabled }}'
false
```
The examples using `podman system service --time=0` starts a podman socket initiated from that command. I think it's more useful to launch in the background rather than …
=> changed: update podman service documentation around network dns

docgen/go.mod, docgen/go.sum, go.mod, go.sum, vendor/go4.org/unsafe/assume-no-moving-gc/assume-no-moving-gc.go, vendor/go4.org/unsafe/assume-no-moving-gc/untested.go, vendor/modules.txt
Fixes build with go 1.20
Closes #1207
go4.org/unsafe/assume-no-moving-gc has to be updated to a version that explicitly defines go 1.20 as safe for this program to build with go 1.20
no changes, the dependency update only marks go 1.20 as supported which fixes the build with go 1.20
this PR is the result of running these commands in the project root and the docgen directory
```
go get go4.org/unsafe/assume-no-moving-gc@v0.0.0-20230209150437-ee73d164e760
go mod tidy
go mod vendor
```
=> change: fix build with go 1.20

docs/usage/k3s.md
I found a broken link in the 'K3s Features in k3d' section
The link points to the (I guess) deprecated /guides/ section. I changed the syntax and made it reference the exposing_services.md for a permanent link
No implications
=> fix: fix for link in doc

.github/workflows/docs.yml, .github/workflows/release.yaml
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
Resolve #1225
=> change: replace deprecated set-output command with environment file in Github Actions

pkg/client/host.go, pkg/runtimes/docker/info.go, pkg/runtimes/types/types.go
k3d mostly works flawlessly on github.com/abiosoft/colima, but host.k3d.interal points to nowhere useful. We detect colima runtime by the name in docker info output, then resolve the host IP by querying host.lima.internal.
How to test:
$ colima start
$ k3d cluster create
$ nc -l 0.0.0.0 1234
In another terminal
$ kubectl run -it --rm --image alpine:latest test --  /bin/sh -c 'echo "hello there" | nc host.k3d.internal 1234'
Fixes HostIP detection when running on Colima.
To fix host.k3d.internal
Unsure. Works on my machine with the patch...
=> fix: handle colima host

.github/workflows/release.yaml, pkg/client/node.go, pkg/types/env.go, pkg/types/fixes/assets/k3d-entrypoint-mounts.sh, pkg/types/fixes/fixes.go
New env var `K3D_FIX_MOUNTS`, set it to e.g. `K3D_FIX_MOUNTS=1` to make `/` in the node containers `rshared` mounts.
This fixes e.g. the setup of Cilium.
If there are no bad implications of this and no one raises issues while using it throughout a few versions, we can add it as a default entrypoint.
#1063
=> add: K3D_FIX_MOUNTS fix to make / rshared (e.g. to make Cilium work)

docs/usage/registries.md
Small typo was fixed.
Example did not work out of the box.
no
=> Correct typo: Inconsistent filename in registry documentation.

cmd/root.go
This adds a flag to be able to return the response of the `version` command and return it as JSON.  
I couldn't find an easier way to parse out what the latest version of K3S that K3D is using easily.
This adds new behavior and should likely not impact any existing other CLI commands.  It does not modify any `pkg` internals.  No breaking changes.
@all-contributors please add @dgershman for code
=> Adds json response of version info

docs/index.md
The PR updates Overview section of documentation to update the ```go install``` command
As mentioned in https://github.com/k3d-io/k3d/issues/1274
The PR does not change any existing behavior of the application. It changes the installation method using ```go``` command
=> docs: update go install command

proxy/Dockerfile
Update alpine to the latest release.
Alpine 3.13.5 has reach end of support and it is cause ORCA to complain
=> change: proxy - update nginx-alpine base image

docs/usage/advanced/podman.md
Document Podman usage in rootless mode on macOS
Follow up to #1257
N/A
=> docs(podman): add usage for rootless mode on macOS

pkg/runtimes/docker/container.go
Not using `io.stdout` directly, instead using the `logger.Out`
It allows control logger output destination - (e.g printing logs to a file)
No known implications
=> Not using stdout directly for logging

README.md, docs/index.md
Reopening #1356. Added k3d scoop package installation option. Scoop is a package manager for Windows.
Scoop is intended to install portable packages like k3d
Only changing docs
=> [DOCS] Add scoop install option

pkg/runtimes/docker/node.go
Haha, you might either laugh or get annoyed at this PR, but...
I've changed the initial Info log regarding node start-up because it seems inconsistent with the other logs.
``` text
...
INFO[0000] Starting Node 'k3d-cluster-tools'
INFO[0001] Creating node 'k3d-cluster-server-0'
...
```
The `Starting Node` log is the only one that's using a starting upper case convention for its object so I thought I'd make it consistent.
What makes this particularly more annoying than just having this inconsistency elsewhere is that this is part of the first command that a newcomer trying out the tool will run, i.e. `k3d cluster create ...`.
=> Consistent logging during cluster creation flow

cmd/cluster/clusterCreate.go, pkg/client/cluster.go, pkg/config/config_test.go, pkg/config/process_test.go, pkg/config/test_assets/baz-ns.yaml, pkg/config/test_assets/config_test_simple.yaml, pkg/config/transform.go, pkg/config/v1alpha5/schema.json, pkg/config/v1alpha5/types.go, pkg/types/files.go, pkg/types/types.go, pkg/util/files.go
This PR introduces embedded manifests in the k3d config file which boosts the portability of the config and makes it easier to share.
So adding an embedded manifest could be as easy as:
```yaml
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
name: my-app
manifests:
- name: my-app-ns.yaml
manifest: |
---
apiVersion: v1
kind: Namespace
metadata:
name: my-app
```
This will be mounted under: `/var/lib/rancher/k3s/server/manifests/embedded/my-app-ns.yaml`.
In addition to the portability, the goal is to make it easy to seed k3d resources, and given that k3s already supports [HelmChart](https://docs.k3s.io/helm) it will be even easier to pre-install any custom packages when the cluster is created.
Fixes https://github.com/k3d-io/k3d/issues/536
Also partially fixes …
=> feat: support config embedded and external files

cmd/config/configInit.go
=> fix: close output file

pkg/types/fixes/assets/k3d-entrypoint-dns.sh
Fixes the use of the `grep` command causing an early fatal exit of the shell script.
In non-Docker and host network environments, this `grep -q` will be fatal and because `-o errexit` is set, the shell script will exit fatally causing the k3s server to fail.
=> fix: Script exits fatally when resolv.conf is missing Docker nameserver

pkg/runtimes/docker/translate.go
This MR make k3d compatible with the [userns-remap](https://docs.docker.com/engine/security/userns-remap/) feature of Docker, like described in [#547](https://github.com/k3d-io/k3d/issues/547).
As a developer, I run container applications from various sources and some run as root in the container.
To strengthen the isolation between the host and the containers, Im interested in leveraging Linux user namespaces.
Here's an example of a security exploit that would be blocked by using user namespaces, according to one of the maintainers of runc:  [CVE-2019-5736](https://seclists.org/oss-sec/2019/q1/119) 
Docker supports user namespaces when the daemon is configured to run with userns-remap.
With this setting enabled, privileged containers need to be created with `userns=host` explicitly.
This …
=> feat: compatibility with docker userns-remap

pkg/runtimes/docker/translate_test.go
This MR updates the expectation of TestTranslateNodeToContainer
https://github.com/k3d-io/k3d/pull/1442 broke the test, my apologies.
None AFAICT
=> test: fix TestTranslateNodeToContainer following #1442

pkg/client/kubeconfig.go
This MR adds support for when the kubeconfig file is a symbolic link.
As reported by this [issue](https://github.com/k3d-io/k3d/issues/1355), the current implementation causes the replacement of the symbolic link by a regular file holding the new/merged config.
Shouldnt change the behavior of anything, beside fixing the bug.
- `git reset --hard && make` is successful
- Successfully created a cluster in the two situations:
- symlink `/home/pierre/.kube/config -> /home/pierre/syncthing/t480s/config/kubectl`
- regular `/home/pierre/.kube/config`
=> fix: dont replace kubeconfig symlink by a file at cluster creation

docs/faq/faq.md, docs/usage/multiserver.md
Delete the outdated explanation in FAQ. Add an instruction in multiserver guide.
I have encountered the same problem and adding the `--subnet` flag solves it.
None
=> docs: mention ipam when creating multiserver cluster

pkg/client/node.go
fixes #1410
When multiple nodes are created, each call to NodeAddToCluster was calling GatherEnvironmentInfo, which was calling EnsureToolsNode() and then deleting the tools node. This causes some type of race condition. The work doesn't need to be done multiple times anyways, so just move it up to NodeAddToClusterMulti and do it once, before kicking off the goroutines.
(Also see #924 and #952 for previous similar issue)
=> fix: call GatherEnvironmentInfo once in NodeAddToClusterMulti to avoid race condition causing error

go.mod, vendor/modules.txt
Cleanup unwanted `replace` directive that was present for `k8s.io/kubelet` that as never really used in the project.
Fixes: #1468
This was breaking `go install` due to the `replace` directive. 
NA
=> bug: fix broken go install workflow

pkg/types/fixes/assets/k3d-entrypoint-cgroupv2.sh
Fixes server start for recent k3s releases.
There was [a change in k3s-root](https://github.com/k3s-io/k3s-root/pull/65), included in k3s 1.30.3-k3s1, which switched to `xargs` from findutils.
The change should be compatible with previous versions of k3s.
```
K3D_HELPER_VERSION=5.7.2 make build
./bin/k3d cluster create old --image rancher/k3s:v1.30.2-k3s1
./bin/k3d cluster stop old
./bin/k3d cluster delete old
./bin/k3d cluster create new --image rancher/k3s:v1.30.3-k3s1
./bin/k3d cluster stop new
./bin/k3d cluster delete new
```
Fixes #1478
=> fix: busybox xargs unlinked on new k3s releases

proxy/Dockerfile
Bumps the base image of the `k3d-proxy` image to resolve various os package vulnerabilities.
Resolves all vulnerabilities mentioned in #1472 
I was unable to test this locally as of yet on my local machine to validate whether or not it causes any issues, will keep trying and update the ticket once I have validation (debugging local go installation issues with running the make files for this repo). If someone can validate easily and comment on ticket it would be appreciated.
=> fix: bump base image of k3d-proxy to resolve vulnerabilities.

pkg/client/node.go, pkg/config/process.go, pkg/types/fixes/fixes.go
=> fix: disable DNS fix in hostnetwork mode

.github/workflows/release.yaml, .github/workflows/test-matrix.yaml, Dockerfile
Bumps the base image of the k3d dind image.
Also refreshes the test matrix to currently supported Docker and k3s (Kubernetes) versions.
I mainly looked at this because we use the k3d dind image as a base image for our controller e2e-tests image. The installed software seemed outdated and I also noticed reported vulnerabilities.
Fixes https://github.com/k3d-io/k3d/issues/1482
Hopefully none - except improving the user experience when using the dind image.
=> fix: bump docker version in dind image

cmd/registry/registryCreate.go, pkg/client/registry.go, pkg/types/registry.go
This PR add the `--delete-enabled` flag to the `k3d registry create` command.
This will activate the storage deletion on the registry and thus allow removal of images.
Administrators will be able to manage the storage used by the registries in a more fine grained way since currently only re-creating the registry would free some space.
Fixes #1541 
Nothing changes with regard to the defaults from the `k3d registry create`
=> feat(registry): add flag to enable storage deletion

pkg/client/cluster.go
Fix #1527 
with tests:
```bash
#conf
- description: 'registry.local-ca.pem'
source: certs/registry/registry.local-ca.pem
destination: /etc/ssl/certs/registry.local-ca.pem
nodeFilters: 
- "agent:0-1"
- "server:*"
#traceLog
TRAC[0000] Filtered 1 nodes (filter: [server:*])        
TRAC[0000] Filtered 1 nodes (filter: [server:*])        
TRAC[0000] Filtered 3 nodes (filter: [agent:0-1 server:*])
#validate
root @ deb1013 in ~ |11:27:14  
$ docker exec -it k3d-mycluster-agent-1 sh
~ # find /etc/ssl/certs/
/etc/ssl/certs/
/etc/ssl/certs/ca-certificates.crt
/etc/ssl/certs/registry.local-ca.pem
```
=> fix: agent-node-files by append agentNode.HookActions

docs/usage/advanced/podman.md
Fixes typo in instructions for configuring k3d with podman on macos
instructions are incorrect
not a breaking change
=> docs: fixes typo for envvar

pkg/config/v1alpha5/schema.json
This pull request moves `registries.properties.additionalproperties` to `registries.additionalProperties`, in accordance with the JSON Schema specification. …
I am creating this pull request because this nonconformance with the JSON Schema specification breaks an integration with a tool that consumes such schemas. The specification confirms that the `additionalProperties` field impacts the interpretation of other fields ([source](https://json-schema.org/draft/2020-12/json-schema-core#name-keyword-independence-2)), suggesting that this is something worth fixing. Examples of the proper usage can be found [here](https://json-schema.org/draft/2020-12/json-schema-core#name-output-structure) and [here](https://json-schema.org/draft/2020-12/json-schema-core#name-verbose). We also see repeated …
=> Update JSON Schema: Correct the location of `additionalProperties` in the `registries` element

cmd/cluster/cluster.go, cmd/debug/debug.go, cmd/node/node.go, pkg/runtimes/docker/docker.go, pkg/runtimes/docker/node.go, pkg/runtimes/docker/util.go, pkg/runtimes/runtime.go
This feature adds an ability to export Cluster logs using the `k3d` binaries.
Tools like `kind` has been supporting the ability to export logs from the cluster using their native tooling for a while. This ability to export the logs using `k3d` can be super helpful when doing local development and test experiments. Instead of having to individually collect the logs, this command can be one stop shop for all standard commands to be aggregated. 
This changes the `Runtime` interface and hence this is a backward incompatible change. 
> If this is an acceptable change to be included, I will be more than happy to take care of including a few more things to the supported export of logs. 
```bash
❯ bin/k3d debug export-logs export-log-test
❯ tree debug-logs-export-log-test/ …
```
=> runtimes: enable log export feature

Makefile, cmd/cluster/clusterCreate.go, cmd/registry/registryCreate.go, cmd/util/ports.go, cmd/util/ports_test.go, pkg/client/registry.go, pkg/config/transform.go, tests/test_registry.sh
makefile changes make sure that the _vendor_ directory is used by the build process (the `GOFLAGS` change) as well as that the local cache isn't needlessly built (both changes) - since there is the said directory.
the code changes fix [issue 1406](https://github.com/k3d-io/k3d/issues/1406), making sure that the internal and external listening ports of the registries match if they are set to a non-default value (and that the Docker port mapping of the registry container is set up correctly as well).
---
when i run the E2E tests locally, 8 of them are failing for a seemingly unrelated reason.   i'd like to be able to see the CI test execution output.
=> fixing the makefile; enforcing the registry port match;

cmd/root.go, docs/usage/commands/k3d_version_list.md
Documentation says that `default excludes pre-releases and arch-specific tags` is default.
s390x is arch specific, it should be excluded by default.
Current behaviour:
```bash
~ k3d version list k3s -i '1.28.4'
v1.28.4-k3s2
v1.28.4-k3s1-s390x
v1.28.4-k3s1
```
=> Exclude s390x as arch-specific tag from version list

docs/faq/faq.md
FAQ example to authenticate docker registry is wrong.
In pod error there is `registry-1.docker.io`, if I use this to authenticate it works fine.
```
Failed to pull image "busybox": failed to pull and unpack image "docker.io/library/busybox:latest":
failed to copy: httpReadSeeker: failed open: unexpected status code 
https://registry-1.docker.io/v2/library/busybox/manifests/sha256:a5d0ce49aa801d475da48f8cb163c354ab95cab073cd3c138bd458fc8257fbf1:
429 Too Many Requests
```
To test this I created two k3d clusters, one with `docker.io`, another with `registry-1.docker.io`.
When docker.io started to hit rate limits, registry-1.docker.io was still working fine.
Test command: `kubectl run pod --image=busybox --command --restart=Never -it --rm -- true`
=> Fix docker registry auth example

docs/usage/configfile.md
Users will most likely install the latest version (v1.31.5-k3s1) that won't work with the old version presented in the documentation (v1.20.4-k3s1).
Update the k3s version shown in the documented configuration file.
I tried using (part of) the documented configuration file with a freshly installed k3d, and it didn't work.
One person discovering k3d might expect documentation to provide a working example, or as close as possible.
It doesn't change any behaviour (100% doc).
@all-contributors please add @AdrienHorgnies for doc
=> docs: show latest available k3s version

cmd/root.go, docs/usage/commands/k3d_version_list.md, go.mod, go.sum, vendor/golang.org/x/mod/LICENSE, vendor/golang.org/x/mod/PATENTS, vendor/golang.org/x/mod/semver/semver.go, vendor/modules.txt
k3d version list uses string comparison instead of version sort. This bring a problem where 1.0 < 1.10 < 1.2.
PR changes sort method to handle semver. Also excludes `dind` and `sha-` from version list by default.
```bash
~ k3d version list k3s -i '1.26' -s desc | grep -v s390x
v1.26.9-k3s1
v1.26.8-k3s1
v1.26.7-k3s1
v1.26.6-k3s1
v1.26.5-k3s1
v1.26.4-k3s1
v1.26.3-k3s1
v1.26.2-k3s1
v1.26.15-k3s1
v1.26.14-k3s1
v1.26.13-k3s2
...
~ k3d version list k3d
sha-05d839b-dind
sha-05d839b
sha-011b299-dind
sha-011b299
sha-0068fbc-dind
sha-0068fbc
enhancement-gh-actions
5.8.2-dind
5.8.2
5.8.1-dind
5.8.1
5.8-dind
5.8
...
```
- output is not sorted properly
- version list contains sha digests and -dind images
=> Use version sort for k3d version list output

pkg/util/files.go
This PR fixes a bug that prevents `files` option in config file from working on windows.
Currently when parsing the config file with `files` option the destination attribute is resolved using the `filepath` package which handles paths based on operating system. This is incorrect for the `destination` attribute as its a path used inside the container and therefore should always be unix style. 
For reference the following config results in the following file inside the server container:
```yaml
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
name: test-cluster
servers: 1
agents: 2
kubeAPI:
host: localhost
image: rancher/k3s:v1.32.3-k3s1
subnet: "172.28.0.0/16"
ports:
- port: 8080:80
nodeFilters:
- loadbalancer
files:
- description: LoadBalancer configuration
source: …
```
=> fix: files option for config on windows

version/version.go
Update the hardcoded k3s version from 1.21 to 1.32
This is overridden at build time in the Makefile but some distros might not use that and fall back to the default version.
This is the case for example for Nix where the user _can_ override the version but if that doesn't happen they default to a very old one (from 2021 or so).
https://github.com/NixOS/nixpkgs/blob/0d36547deb33d32f05add583384ae5858dadb464/pkgs/by-name/k3/k3d/package.nix#L6
This just updates the default version to the current stable k3s version.
It changes the default version of k3s for users which build k3d themselves without using the Makefile or with custom changes to it.
=> Update the hardcoded k3s version from 1.21 to 1.32

pkg/types/fixes/fixes.go
This PR fixes the behavior reported in the issue #1449 by disabling the DNS fix when running on the [Colima runtime](https://github.com/abiosoft/colima).
Without this PR, whenever a new cluster is built, Docker images are not downloaded because the DNS is not reachable. This can be fixed by using the `K3D_FIX_DNS=0` but it would be better if it would work out of the box.
This PR doesn't change anything for those who already use the fix mentioned above. It only helps new users to make their cluster running without having to look for a solution for the broken DNS.
=> Skip DNS fix on Colima

cmd/cluster/clusterCreate.go, cmd/registry/registryCreate.go, cmd/util/ports.go, cmd/util/ports_test.go, pkg/client/registry.go, pkg/config/transform.go, pkg/config/v1alpha5/schema.json, pkg/config/v1alpha5/types.go, pkg/types/registry.go
i'm addressing [issue 1406](https://github.com/k3d-io/k3d/issues/1406) again, but this time it's a flag to be explicitly provided, in order not to affect the existing usage.
i've altered CLI registry creation as well as cluster CLI- and config-based creation.
the `REGISTRY_HTTP_ADDR` environment variable handles the default registry image as well as the [k3d-registry-dockerd](https://github.com/ligfx/k3d-registry-dockerd) image.
as discussed - i want to see the E2E tests pass.
=> feat(1406): introducing the option to match registry ports;

cmd/cluster/clusterEdit.go, cmd/node/nodeEdit.go, pkg/client/cluster.go, pkg/client/loadbalancer.go, pkg/client/node.go, pkg/client/ports.go, pkg/config/v1alpha5/types.go, pkg/util/util.go, tests/test_node_edit.sh
- purely additive change, a new flag, implementing [1570](https://github.com/k3d-io/k3d/issues/1570).
- tested with all possible node filters, as well as port ranges.   node suffixes seem to be disallowed in the `cluster edit` command.
- the `PortWithNodeFilters` type was already quite case-specific one, so i figured adding the flag there to carry it deeper into the code was acceptable.
=> feat(https://github.com/k3d-io/k3d/issues/1570): introducing the --port-delete flag;
