main.go

I find myself typing ls often by accident, how about an alias?

Add ls and l alias to list

---

.travis.yml
Makefile
README.md
go.mod
install.sh
main.go

rename repository from `iwilltry42/k3d` to `rancher/k3d` and add @zeerorg and @ibuildthecloud as authors to cli

Migrate to rancher

---

.travis.yml
Makefile
README.md
cli/commands.go
go.mod
install.sh
main.go

**What changed?**
* Migration from `iwilltry42/k3d` to `rancher/k3d`
* Re-ordered the arguments for the docker command in `CreateCluster` function
* New Flags for `create` command:
- `--env`, `-e` for passing additional environment variables to docker
- `--server-arg`, `-x` for passing additional  arguments to the k3s server command
* Shorthand notation for `delete` command: `-del`

Migration to Rancher space and new features

---

README.md

This PR fix bad go get command in the readme

Fix bad go get command in the readme

---

cli/commands.go
cli/container.go
main.go

[Feature] add --image/-i flag to specify custom k3s image

---

cli/config.go

Minor improvements, nothing major.  Please see commit messages of each individual patch for details.

[Enhancement] Improve the output of the k3d list command.

---

cli/commands.go
cli/config.go

Attempt to fix #42.  With some API refactoring and code simplification.

[bugfix] Bug42

---

Makefile
cli/config.go
cli/port.go
main.go

Makefile improvements to sure that 'make fmt' and 'make simplify' works. 
'make check' works the way it is today. It needs more work to be able to check all sources. At the moment, I am not able to make it work on my laptop.

[Enhancement] Makefile

---

Makefile
cli/container.go

Refactoring Makefile to make sure lint and check targets work.

[Enhancement] Makefile: Add lint target and factor the check target

---

README.md
docs/documentation.md
docs/examples.md
docs/faq.md

Extracted from #57 to prepare a path for proper documentation.

[Docs] Prepare for proper documentation

---

cli/commands.go
cli/container.go
cli/port.go
cli/util.go
cli/volume.go

Allow volume binds to specific nodes with `--volume src:dest@node-name`
Fixes #85

Add node-specifier for volumes

---

README.md

readme: add brew install instructions

---

docs/examples.md

Update the documentation template for the insecure registry example

---

cli/registry.go

It seems this fixes the registry detection in Travis... :confused:

[FIX] Fix the Registry detection

---

cli/container.go
tests/01-basic.sh
tests/common.sh
tests/fixtures/01-registries-empty.yaml

[Fix] Do not try to write the registries.yaml if --enable-registry has not been provided

---

cli/commands.go
cli/util.go

We are always printing the `Make sure you have an alias in your /etc/hosts file like '127.0.0.1 registry.local` message, even if `registry.local` can already be resolved. This skips that message when the name `registry.local` can be resolved (in a really short amount of time).

[Enhancement] Do not print the /etc/hosts message if the registry name can be resolved

---

go.mod
go.sum
main.go

logrus by default sets its output to stderr. this PR will change k3d to log to stdout by default instead of stderr.

[Enhancement] default log output to stdout not stderr

---

cli/commands.go
docs/registries.md
main.go
tests/02-registry.sh

[Enhancement] use .localhost as a default registry name

---

README.md

Added a link to the AUR package in README.md

---

Makefile

installScript: fix duplication in curl command

---

cmd/create/createCluster.go
cmd/util/volumes.go
pkg/runtimes/containerd/volume.go
pkg/runtimes/docker/volume.go
pkg/runtimes/runtime.go

fix: re-add support for named volumes used with --volume flag

---

docs/static/css/extra.css

fixing current section alignment in main nav

header fix

---

cmd/cluster/clusterCreate.go
cmd/cluster/clusterList.go
cmd/cluster/clusterStart.go
cmd/node/nodeCreate.go
cmd/node/nodeStart.go
cmd/node/nodeStop.go
cmd/util/completion.go
cmd/util/filter.go
docs/faq/faq.md
docs/index.md
docs/internals/defaults.md
docs/internals/networking.md
docs/usage/.pages
docs/usage/commands.md
docs/usage/guides/exposing_services.md
docs/usage/multimaster.md
pkg/cluster/cluster.go
pkg/cluster/kubeconfig.go
pkg/cluster/loadbalancer.go
pkg/cluster/node.go
pkg/runtimes/docker/translate.go
pkg/runtimes/docker/translate_test.go
pkg/tools/tools.go
pkg/types/types.go
proxy/templates/nginx.tmpl
tests/test_full_lifecycle.sh
tests/test_multi_master.sh
thoughts.md

[Enhancement] Inclusive terminology: use server/agent instead of master/worker

---

cmd/cluster/clusterList.go
pkg/types/types.go

Represent the availability of the load balancer in the cluster list:
For you @nunix :wink:

[FEATURE] clusterList: add bool for loadbalancer

---

pkg/cluster/cluster.go
proxy/templates/nginx.tmpl

[Enhancement] allow allow port-ranges on the loadbalancer

---

pkg/cluster/cluster.go

Fixes #310 
Potential issues (though unlikely): server (or serverlb) node is running already, but in some broken state, where it's not usable.

[Fix] clusterStart: hangs forever when trying to start a node that's already running (waiting for log message)

---

cmd/root.go

Adds completions for fish shell, via cobra

(feature) Add fish shell completions

---

docs/index.md

You can also use `asdf` for a quick'n'easy install.

Add asdf install option

---

docs/usage/guides/calico.md
docs/usage/guides/calico.yaml
docs/usage/guides/cuda.md
mkdocs.yml
pkg/cluster/cluster.go
pkg/tools/tools.go

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/k3d/commit/57f34581bca62c49359b3f3de141a723f4edb735#commitcomment-45541885
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/k3d/commit/63f4efc546c98b5280cd39f2f4c05f14ccf028f9
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

docs: spell checking (#434, @jsoref)

---

CHANGELOG.md
pkg/client/cluster.go
pkg/client/registry.go
pkg/client/registry_test.go
pkg/client/test.json
pkg/types/k8s/registry.go
tests/test_registry.sh

[Feature] add LocalRegistryHostingV1 from KEP-1755

---

pkg/util/filter.go

[Fix] nil-pointer exception when eyposing port on loadbalancer with --no-lb set

---

cmd/cluster/clusterCreate.go
docs/usage/guides/registries.md
pkg/client/cluster.go
pkg/client/registry.go
pkg/config/transform.go
pkg/config/v1alpha1/types.go
pkg/types/types.go
pkg/util/filter.go
tests/assets/config_test_simple.yaml
tests/assets/test_registries.yaml
tests/common.sh
tests/test_config_file.sh
tests/test_full_lifecycle.sh

[Feature] Allow k3d-managed + externally configured registries at the same time

---

README.md
docs/index.md

In order to our [discussion](https://github.com/rancher/k3d/issues/463#issuecomment-773242642), I'm adding [k3d-action (https://github.com/AbsaOSS/k3d-action)](https://github.com/AbsaOSS/k3d-action) between related projects.

Docs: link to GitHub k3d-action (#476, @kuritka)

---

cmd/registry/registryCreate.go
docs/usage/guides/registries.md

k3d's behavior to add the `k3d-` prefix to all resources it creates, led to some confusion around the usage of k3d-managed registries as described in #509.
This PR adds an explanatory help text and clarifies the documentation around this topic.
Fixes #509

[Enhancement] docs/help: clarify registry names (naming & k3d-prefix)

---

docs/internals/networking.md

Replaces missing left (their right) arm on Shruggie.
The floating hand with no arm was a little disconcerting when reading through the docs.
No changes to behavior, documentation only.

[Docs] Heal Shruggie: Replace amputated arm (#540, @claycooper)

---

docs/usage/configfile.md

Typo in docs
The less typos in docs, the better ;)
None

[DOCS] fix typo

---

docs/faq/faq.md

Fixes a url typo in the FAQ.
Was looking through docs and noticed a broken link.
No implications.

[DOCS] fix typo in url (#561, @alechartung)

---

proxy/conf.d/nginx.toml
proxy/templates/nginx.tmpl

[FIX] proxy: rename udp specific upstreams

---

docs/usage/configfile.md

docs: usage/configfile typo

---

docs/faq/faq.md

Ref: #594
Addition to FAQ
Observation might help others
None

[Doc] Addition to FAQ about spurious PID entries (#609, @leelavg)

---

README.md
docs/index.md

Hi, we have just developed a lightweight tool AutoK3s to help run K3s everywhere including k3d provider

docs: link to github autoK3s (#614, @jaciechao)

---

README.md
docs/index.md

Mention "nolar/setup-k3d-k3s" step for GitHub Actions.

Mention "nolar/setup-k3d-k3s" step for GitHub Actions (#668, @nolar)

---

pkg/client/cluster.go
pkg/runtimes/docker/util.go

Follow-Up for #601 
FYI @developer-guy , can you please give this a try?

[Fix] Simplify and Fix docker client creation

---

cmd/config/configMigrate.go
pkg/config/v1alpha3/migrations.go
pkg/util/util.go
tests/assets/config_test_simple_migration_v1alpha2.yaml

missing migration of `[index]` to `:index`
Fixes #766

[Fix] `k3d config migrate` missing nodefilter migration

---

pkg/actions/nodehooks.go
pkg/client/cluster.go
pkg/client/node.go
pkg/types/types.go

- nodeHooks: add Description field and Name()/Info() functions
- nodeAddToCluster: add host.k3d.internal /etc/Hosts injection as postStartAction
- fixes #781

[Enhancement] `node create` add `host.k3d.internal` entry to `/etc/hosts` + enhance `NodeHooks`

---

tests/common.sh
tests/extra_test_k3s_versions.sh
tests/runner.sh
tests/test_basic.sh
tests/test_config_file.sh
tests/test_config_file_migration.sh
tests/test_config_with_overrides.sh
tests/test_full_lifecycle.sh
tests/test_ipam.sh
tests/test_loadbalancer.sh
tests/test_memory_limits.sh
tests/test_multi_master.sh
tests/test_multi_master_start_stop.sh
tests/test_node_edit.sh
tests/test_registry.sh

- run up to 4 tests in parallel
- send all logs to files
- output only logs of failed tests

[Enhancement] tests/e2e: speedup & cleanup

---

docs/design/.pages
docs/design/concepts.md

- contains nodefilters
fixes #887

docs: add page about k3d concepts (incl. nodefilters)

---

README.md

Signed-off-by: Derek Nola <derek.nola@suse.com>
README Change
Point to changed K3s Repo.
Wording :)

Update readme with k3s-io

---

docs/usage/advanced/.pages
docs/usage/advanced/podman.md

Needs #986, closes #84 
Adds documentation for using k3d on Podman (rootful and rootless)
See #84.
- Users will expect k3d + Podman to work flawlessly
- Added a warning that this is experimental
- Write integration tests

docs: Podman (rootful/rootless) usage docs

---

docs/usage/configfile.md

fix #36
https://github.com/k3d-io/k3d/issues/36#issuecomment-1425868978

change: update docs to use quotes around extra args

---

docs/usage/advanced/podman.md

Add instructions to documentation for podman on macOS
add documentation for Podman on macOS
Because it didn't work ootb and this worked for me
just makes it easier for future macOS/podman users

add(docs): podman instructions for macOS

---

go.mod
go.sum
go.work.sum
pkg/config/transform.go
vendor/github.com/rancher/wharfie/pkg/registries/types.go
vendor/modules.txt

To be changed if https://github.com/rancher/wharfie/pull/17 gets merged

fix: custom registry config not parsed correctly

---

docs/usage/commands/k3d_cluster_create.md

Fixes markdown and mkdocs list formatting
@all-contributors please add @stratusjerry for doc

docs: fix list failing to render

---

docs/usage/commands/k3d_image_import.md

change: fix docs link

---

cmd/util/runtimeLabels.go
pkg/runtimes/docker/node.go
pkg/util/filter.go

make function comments match function names

chore: make function comments match function names
